version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/code/service-account.json" # Ruta en el contenedor
    volumes:
      - .:/code
      - /tmp/service-account.json:/code/service-account.json
