version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_CREDENTIALS_JSON}"
    volumes:
      - .:/code
      - /code/temp_files
