name: "💡 Feature Request"
description: "Request a new feature or enhancement for the project"
title: "💡 [Feature] - <Title>"
labels: 
  - "feature"
  - "enhancement"
body:
  - type: textarea
    id: summary
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the feature you are requesting."
      placeholder: "Write a short summary of the feature."
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "Explain how this feature will add value to the project."
      placeholder: "Describe why this feature is important."
    validations:
      required: true
  - type: textarea
    id: implementation_idea
    attributes:
      label: "Implementation Idea"
      description: "Provide any ideas or suggestions for how this feature could be implemented."
      placeholder: "Share your thoughts on possible solutions."
    validations:
      required: false
  - type: textarea
    id: potential_drawbacks
    attributes:
      label: "Potential Drawbacks"
      description: "List any possible risks or negative impacts of this feature."
      placeholder: "Identify challenges or downsides."
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: "References or Related Issues"
      description: "Provide links to relevant issues, pull requests, or documentation."
      placeholder: "e.g., #123 or external documentation links."
    validations:
      required: false
