name: Auto-Assign Issue Creator

on:
  issues:
    types: [opened] # Solo se activa cuando se abre un issue.

jobs:
  auto_assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign issue to creator
      uses: actions-ecosystem/action-add-issue-assignees@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.actor }}
