name: Auto assign issue creator

on:
  issues:
    types:
      - opened

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Assign issue creator
        uses: gustavofreze/auto-assign@1.0.0
        with:
          assignees: '${{ github.actor }}'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          assignment_options: 'ISSUE'
          allow_self_assign: 'true'
          allow_no_assignees: 'false'