name: CI/CD Pipeline with Docker Compose and Terraform

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install docker-compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/service-account.json
          cat /tmp/service-account.json  # Mostrar el contenido del archivo de credenciales (puedes quitar esta línea después de probar)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Print environment variables
        run: |
          echo "GCP Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Service Account Email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}"

  development:
    runs-on: ubuntu-latest
    environment: development
    needs: common-setup
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Terraform Init and Plan
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="service_account_email=${{ secrets.SERVICE_ACCOUNT_EMAIL }}"
          cat tfplan  # Mostrar el plan de Terraform antes de aplicar

      - name: Build and start Docker containers for development
        run: |
          docker-compose -f docker-compose.yml -p development up --build -d
          docker-compose ps  # Ver los contenedores en ejecución para asegurarse de que todo está bien

      - name: Run tests inside containers
        run: |
          docker-compose exec app pytest  # Run tests inside the app container

      - name: Clean up Docker Compose services
        run: |
          docker-compose down --volumes --remove-orphans

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: common-setup
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="service_account_email=${{ secrets.SERVICE_ACCOUNT_EMAIL }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json

      - name: Build and start Docker containers for production
        run: |
          docker-compose -f docker-compose.yml -p production up --build -d
          docker-compose ps  # Ver los contenedores en ejecución para asegurarse de que todo está bien

      - name: Run tests inside containers
        run: |
          docker-compose exec app pytest  # Run tests inside the app container

      - name: Clean up Docker Compose services
        run: |
          docker-compose down --volumes --remove-orphans
