name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'

jobs:
  development:
    runs-on: ubuntu-latest
    environment: development
    if: github.ref == 'refs/heads/develop'

    steps:
      # 1. Chequea el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala Docker y Docker Compose
      - name: Set up Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      # 3. Configura Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 4. Instala las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Configura el secreto GOOGLE_APPLICATION_CREDENTIALS
      - name: Set up Google credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/service-account.json

      # 6. Ejecuta el contenedor Docker
      - name: Build and run Docker container
        run: |
          docker-compose up --build -d

      # 7. Realiza pruebas (si corresponde)
      - name: Run tests
        run: |
          docker exec <container_name> pytest

      # 8. Detiene el contenedor después de las pruebas
      - name: Stop Docker container
        run: |
          docker-compose down
