name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display secret
        run: |
          echo "Secret value: ${{ secrets.name }}"